In [4]:
import numpy as np

# 1. 활성화 함수 (Sigmoid) 및 도함수 정의
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    # Sigmoid 미분: sigmoid(x) * (1 - sigmoid(x))
    s = sigmoid(x)
    return s * (1 - s)

# 2. 데이터 준비 (입력 4개 샘플, 특성 3개 / 출력 1개)
np.random.seed(42)
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])  # Shape: (4, 3)

y = np.array([[0], 
              [1], 
              [1], 
              [0]])       # Shape: (4, 1) - 타겟 정답

# 3. 하이퍼파라미터 및 가중치 초기화
input_size = 3    # 입력층 노드 수
hidden_size = 4   # 은닉층 노드 수
output_size = 1   # 출력층 노드 수
learning_rate = 1.0
epochs = 10000

# 가중치 초기화 (랜덤값)
W1 = np.random.randn(input_size, hidden_size)  # Shape: (3, 4)
b1 = np.zeros((1, hidden_size))                # Shape: (1, 4)

W2 = np.random.randn(hidden_size, output_size) # Shape: (4, 1)
b2 = np.zeros((1, output_size))                # Shape: (1, 1)

# 4. 학습 루프 (Forward & Backward)
for epoch in range(epochs):
    # ==========================================
    # [1] 순전파 (Forward Propagation)
    # ==========================================
    # 은닉층
    z1 = np.dot(X, W1) + b1                   # z^(1) = W^(1)x + b^(1)
    a1 = sigmoid(z1)                          # a^(1) = sigma(z^(1))

    # 출력층
    z2 = np.dot(a1, W2) + b2                  # z^(2) = W^(2)a^(1) + b^(2)
    a2 = sigmoid(z2)                          # a^(2) = y_hat = sigma(z^(2))

    # 손실 계산 (MSE)
    loss = np.mean(0.5 * (a2 - y) ** 2)

    # ==========================================
    # [2] 오차 역전파 (Backward Propagation)
    # ==========================================
    # 출력층 오차 신호: delta^(2) = (dL/da2) * sigma'(z2)
    dL_da2 = (a2 - y)
    delta2 = dL_da2 * sigmoid_derivative(z2)
    
    # 출력층 가중치 및 편향 기울기
    dW2 = np.dot(a1.T, delta2)                # dL/dW^(2) = (a^(1))^T * delta^(2)
    db2 = np.sum(delta2, axis=0, keepdims=True)

    # 은닉층 오차 신호: delta^(1) = (delta^(2) * (W^(2))^T) * sigma'(z1)
    delta1 = np.dot(delta2, W2.T) * sigmoid_derivative(z1)
    
    # 은닉층 가중치 및 편향 기울기
    dW1 = np.dot(X.T, delta1)                 # dL/dW^(1) = X^T * delta^(1)
    db1 = np.sum(delta1, axis=0, keepdims=True)

    # ==========================================
    # [3] 가중치 업데이트 (Gradient Descent)
    # ==========================================
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    # 학습 경과 출력
    if (epoch + 1) % 2000 == 0:
        print(f"Epoch {epoch+1:5d} | Loss: {loss:.6f}")

print("\n--- 학습 후 예측 결과 ---")
print(a2)

Epoch  2000 | Loss: 0.000314
Epoch  4000 | Loss: 0.000138
Epoch  6000 | Loss: 0.000087
Epoch  8000 | Loss: 0.000064
Epoch 10000 | Loss: 0.000050

--- 학습 후 예측 결과 ---
[[0.00859907]
 [0.98964122]
 [0.99024546]
 [0.01102826]]


In [23]:
x[:,::2]


array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [22]:
x = np.array(range(15),int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
x[1:3]


array([[ 6,  7,  8,  9, 10]])

In [20]:
x[1,1:3]

array([7, 8])

In [19]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
x[:, 2:]


array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [16]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
tensor_rank3 = [
       [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
       [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
       [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
       [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
       ]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [10]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [9]:
import numpy as np
test_array = np.array([1,4,5,8])
print(test_array)
print(type(test_array))
print(type(test_array.dtype))

[1 4 5 8]
<class 'numpy.ndarray'>
<class 'numpy.dtypes.Int64DType'>


In [8]:
import numpy as np
test_array = np.array([1,4,5,"8"])
print(test_array)
print(type(test_array))
print(type(test_array[3]))

['1' '4' '5' '8']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [7]:
import numpy as np
test_array = np.array([1,4,5,8])
print(test_array)
print(type(test_array))
print(type(test_array[3]))


[1 4 5 8]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [4]:
import numpy as np
test_array = np.array([1,4,5,8],float)
print(test_array)
print(type(test_array))
print(type(test_array[3]))


[1. 4. 5. 8.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
